// ------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン: 17.0.0.0
//  
//     このファイルへの変更は、正しくない動作の原因になる可能性があり、
//     コードが再生成されると失われます。
// </auto-generated>
// ------------------------------------------------------------------------------
namespace UnitGenerator
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class CodeTemplate : CodeTemplateBase
    {
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("// <auto-generated>\r\n// THIS (.cs) FILE IS GENERATED BY UnitGenerator. DO NOT CHA" +
                    "NGE IT.\r\n// </auto-generated>\r\n#pragma warning disable CS8669\r\nusing System;\r\n");
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write(" \r\nusing MessagePack;\r\nusing MessagePack.Formatters;\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write(" \r\nusing System.Text.Json;\r\nusing System.Text.Json.Serialization;\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.DapperTypeHandler)) { 
            this.Write(" \r\nusing System.Runtime.CompilerServices;\r\n");
 } 
            this.Write("\r\n");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("namespace ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            this.Write("\r\n{\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write(" \r\n    [JsonConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("JsonConverter))]\r\n");
 } 
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write(" \r\n    [MessagePackFormatter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("MessagePackFormatter))]\r\n");
 } 
            this.Write("    [System.ComponentModel.TypeConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeConverter))]\r\n    readonly partial struct ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" : IEquatable<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("> ");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.Comparable) ? $", IComparable<{Name}>" : ""));
            this.Write("\r\n    {\r\n        readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value;\r\n\r\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" AsPrimitive() => value;\r\n\r\n        public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value)\r\n        {\r\n            this.value = value;\r\n");
 if (HasFlag(UnitGenerateOptions.Validate)) { 
            this.Write(" \r\n            this.Validate();\r\n");
 } 
            this.Write("        }\r\n\r\n");
 if (HasFlag(UnitGenerateOptions.Validate)) { 
            this.Write(" \r\n        private partial void Validate();\r\n");
 } 
            this.Write("\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.ImplicitOperator) ? "implicit" : "explicit"));
            this.Write(" operator ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value)\r\n        {\r\n            return value.value;\r\n        }\r\n\r\n        public " +
                    "static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(HasFlag(UnitGenerateOptions.ImplicitOperator) ? "implicit" : "explicit"));
            this.Write(" operator ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value)\r\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(value);\r\n        }\r\n\r\n        public bool Equals(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" other)\r\n        {\r\n            return value.Equals(other.value);\r\n        }\r\n\r\n " +
                    "       public override bool Equals(object obj)\r\n        {\r\n            if (obj =" +
                    "= null) return false;\r\n            var t = obj.GetType();\r\n            if (t == " +
                    "typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("))\r\n            {\r\n                return Equals((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(")obj);\r\n            }\r\n            if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("))\r\n            {\r\n                return value.Equals((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")obj);\r\n            }\r\n\r\n            return value.Equals(obj);\r\n        }\r\n\r\n    " +
                    "    public override int GetHashCode()\r\n        {\r\n            return value.GetHa" +
                    "shCode();\r\n        }\r\n\r\n        public override string ToString()\r\n        {\r\n");
 if (ToStringFormat == null) { 
            this.Write("            return value.ToString();\r\n");
 } else { 
            this.Write("            return string.Format(\"");
            this.Write(this.ToStringHelper.ToStringWithCulture(ToStringFormat));
            this.Write("\", value);\r\n");
 } 
            this.Write("        }\r\n\r\n        public static bool operator ==(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            return x.value.Equals(y.value);\r\n        }\r\n\r\n       " +
                    " public static bool operator !=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            return !x.value.Equals(y.value);\r\n        }\r\n\r\n");
 if (Type == "Guid" || Type == "System.Guid") { 
            this.Write("        public static readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Empty = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New()\r\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Guid.NewGuid());\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("()\r\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Guid.NewGuid());\r\n        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (Type == "Ulid" || Type == "System.Ulid") { 
            this.Write("        public static readonly ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Empty = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\r\n        \r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New()\r\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Ulid.NewUlid());\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" New");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("()\r\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Ulid.NewUlid());\r\n        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.ParseMethod)) { 
            this.Write(" \r\n        // UnitGenerateOptions.ParseMethod\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Parse(string s)\r\n        {\r\n");
 if (Type == "string") { 
            this.Write("            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(s);\r\n");
 } else { 
            this.Write("            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(s));\r\n");
 } 
            this.Write("        }\r\n        \r\n        public static bool TryParse(string s, out ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" result)\r\n        {\r\n");
 if (Type == "string") { 
            this.Write("            try\r\n            {\r\n                result = Parse(s);    \r\n         " +
                    "       return true;\r\n            } \r\n            catch \r\n            {\r\n        " +
                    "        result = default;\r\n                return false;\r\n            }\r\n");
 } else { 
            this.Write("            if(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".TryParse(s, out var r))\r\n            {\r\n                result = new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(r);\r\n                return true;\r\n            }\r\n            else\r\n            " +
                    "{\r\n                result = default(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\r\n                return false;\r\n            }\r\n");
 } 
            this.Write("        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.MinMaxMethod)) { 
            this.Write(" \r\n        // UnitGenerateOptions.MinMaxMethod\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Min(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Math.Min(x.value, y.value));\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Max(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(Math.Max(x.value, y.value));\r\n        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (Type == "bool") { 
            this.Write("        // Default\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator true(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        {\r\n            return x.value;\r\n        }\r\n        \r\n        public " +
                    "static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator false(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        {\r\n            return !x.value;\r\n        }\r\n        \r\n        public" +
                    " static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" operator !(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        {\r\n            return !x.value;\r\n        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.ArithmeticOperator)) { 
            this.Write(" \r\n        // UnitGenerateOptions.ArithmeticOperator\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator +(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value + y.value));\r\n            }\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator -(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value - y.value));\r\n            }\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator *(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value * y.value));\r\n            }\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator /(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value / y.value));\r\n            }\r\n        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.ValueArithmeticOperator)) { 
            this.Write(" \r\n        // UnitGenerateOptions.ValueArithmeticOperator\r\n\r\n        public stati" +
                    "c ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator ++(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value + 1));\r\n            }\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator --(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value - 1));\r\n            }\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator +(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value + y));\r\n            }\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator -(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value - y));\r\n            }\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator *(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value * y));\r\n            }\r\n        }\r\n\r\n        public static ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" operator /(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" y)\r\n        {\r\n            checked\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")(x.value / y));\r\n            }\r\n        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.Comparable)) { 
            this.Write(" \r\n        // UnitGenerateOptions.Comparable\r\n\r\n        public int CompareTo(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" other)\r\n        {\r\n            return value.CompareTo(other.value);\r\n        }\r\n" +
                    "\r\n");
 if (!HasFlag(UnitGenerateOptions.WithoutComparisonOperator)) { 
            this.Write("         \r\n        \r\n        public static bool operator >(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            return x.value > y.value;\r\n        }\r\n\r\n        publi" +
                    "c static bool operator <(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            return x.value < y.value;\r\n        }\r\n\r\n        publi" +
                    "c static bool operator >=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            return x.value >= y.value;\r\n        }\r\n\r\n        publ" +
                    "ic static bool operator <=(in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" x, in ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" y)\r\n        {\r\n            return x.value <= y.value;\r\n        }\r\n");
 } 
            this.Write("\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.JsonConverter)) { 
            this.Write(" \r\n        // UnitGenerateOptions.JsonConverter\r\n        private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("JsonConverter : JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\r\n        {\r\n            public override void Write(Utf8JsonWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, JsonSerializerOptions options)\r\n            {\r\n                var conver" +
                    "ter = options.GetConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")) as JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">;\r\n                if (converter != null)\r\n                {\r\n                  " +
                    "  converter.Write(writer, value.value, options);\r\n                }\r\n           " +
                    "     else\r\n                {\r\n                    throw new JsonException($\"{typ" +
                    "eof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")} converter does not found.\");\r\n                }\r\n            }\r\n        \r\n    " +
                    "        public override ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions option" +
                    "s)\r\n            {\r\n                var converter = options.GetConverter(typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")) as JsonConverter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">;\r\n                if (converter != null)\r\n                {\r\n                  " +
                    "  return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(converter.Read(ref reader, typeToConvert, options));\r\n                }\r\n       " +
                    "         else\r\n                {\r\n                    throw new JsonException($\"" +
                    "{typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")} converter does not found.\");\r\n                }\r\n            }\r\n\r\n");
if (HasFlag(UnitGenerateOptions.JsonConverterDictionaryKeySupport)) {  
            this.Write("            public override void WriteAsPropertyName(Utf8JsonWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, JsonSerializerOptions options)\r\n            {\r\n");
if (IsSupportUtf8Formatter()) {  
            this.Write(@"                Span<byte> buffer = stackalloc byte[36];
                if (System.Buffers.Text.Utf8Formatter.TryFormat(value.value, buffer, out var written))
                {
                    writer.WritePropertyName(buffer.Slice(0, written));
                }
                else
                {
                    writer.WritePropertyName(value.value.ToString());
                }
");
 } else if (IsUlid()) { 
            this.Write("                writer.WritePropertyName(value.value.ToString());\r\n");
 } else { 
            this.Write("                writer.WritePropertyName(value.value.ToString());\r\n");
 } 
            this.Write("            }\r\n\r\n            public override ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" ReadAsPropertyName(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializer" +
                    "Options options)\r\n            {\r\n");
if (IsSupportUtf8Formatter()) {  
            this.Write("                if (System.Buffers.Text.Utf8Parser.TryParse(reader.ValueSpan, out" +
                    " ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(" value, out var consumed))\r\n                {\r\n                    return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(value);\r\n                }\r\n                else\r\n                {\r\n           " +
                    "         return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\r\n                }\r\n");
 } else if (IsUlid()) { 
            this.Write("                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\r\n");
 } else if(Type == "string")  { 
            this.Write("                    return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(reader.GetString());\r\n");
 } else { 
            this.Write("                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(".Parse(reader.GetString()));\r\n");
 } 
            this.Write("            }\r\n\r\n");
 } 
            this.Write("\r\n        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.MessagePackFormatter)) { 
            this.Write(" \r\n        // UnitGenerateOptions.MessagePackFormatter\r\n        private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("MessagePackFormatter : IMessagePackFormatter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\r\n        {\r\n            public void Serialize(ref MessagePackWriter writer, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value, MessagePackSerializerOptions options)\r\n            {\r\n                opt" +
                    "ions.Resolver.GetFormatterWithVerify<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">().Serialize(ref writer, value.value, options);\r\n            }\r\n\r\n            pu" +
                    "blic ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Deserialize(ref MessagePackReader reader, MessagePackSerializerOptions options)\r" +
                    "\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(options.Resolver.GetFormatterWithVerify<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">().Deserialize(ref reader, options));\r\n            }\r\n        }\r\n\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.DapperTypeHandler)) { 
            this.Write(" \r\n        // UnitGenerateOptions.DapperTypeHandler\r\n        public class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeHandler : Dapper.SqlMapper.TypeHandler<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(">\r\n        {\r\n            public override ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" Parse(object value)\r\n            {\r\n                return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(")value);\r\n            }\r\n\r\n            public override void SetValue(System.Data." +
                    "IDbDataParameter parameter, ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(" value)\r\n            {\r\n                parameter.DbType = System.Data.DbType.");
            this.Write(this.ToStringHelper.ToStringWithCulture(GetDbType()));
            this.Write(";\r\n                parameter.Value = value.value;\r\n            }\r\n        }\r\n\r\n  " +
                    "      [ModuleInitializer]\r\n        public static void AddTypeHandler()\r\n        " +
                    "{\r\n            Dapper.SqlMapper.AddTypeHandler(new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(".");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeHandler());\r\n        }\r\n");
 } 
            this.Write("\r\n");
 if (HasFlag(UnitGenerateOptions.EntityFrameworkValueConverter)) { 
            this.Write(" \r\n        // UnitGenerateOptions.EntityFrameworkValueConverter\r\n        public c" +
                    "lass ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("ValueConverter : Microsoft.EntityFrameworkCore.Storage.ValueConversion.ValueConve" +
                    "rter<");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(", ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(">\r\n        {\r\n            public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("ValueConverter()\r\n                : base(\r\n                        convertToProvi" +
                    "derExpression: x => x.value,\r\n                        convertFromProviderExpress" +
                    "ion: x => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(x))\r\n            {\r\n            }\r\n\r\n            public ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@"ValueConverter(Microsoft.EntityFrameworkCore.Storage.ValueConversion.ConverterMappingHints mappingHints = null)
                : base(
                        convertToProviderExpression: x => x.value,
                        convertFromProviderExpression: x => new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("(x),\r\n                        mappingHints: mappingHints)\r\n            {\r\n       " +
                    "     }\r\n        }\r\n\r\n");
 } 
            this.Write("        // Default\r\n        private class ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("TypeConverter : System.ComponentModel.TypeConverter\r\n        {\r\n            priva" +
                    "te static readonly Type WrapperType = typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(");\r\n            private static readonly Type ValueType = typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@");

            public override bool CanConvertFrom(System.ComponentModel.ITypeDescriptorContext context, Type sourceType)
            {
                if (sourceType == WrapperType || sourceType == ValueType)
                {
                    return true;
                }

                return base.CanConvertFrom(context, sourceType);
            }

            public override bool CanConvertTo(System.ComponentModel.ITypeDescriptorContext context, Type destinationType)
            {
                if (destinationType == WrapperType || destinationType == ValueType)
                {
                    return true;
                }

                return base.CanConvertTo(context, destinationType);
            }

            public override object ConvertFrom(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value)
            {
                if (value != null)
                {
                    var t = value.GetType();
                    if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("))\r\n                    {\r\n                        return (");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(")value;\r\n                    }\r\n                    if (t == typeof(");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write("))\r\n                    {\r\n                        return new ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write("((");
            this.Write(this.ToStringHelper.ToStringWithCulture(Type));
            this.Write(@")value);
                    }
                }

                return base.ConvertFrom(context, culture, value);
            }

            public override object ConvertTo(System.ComponentModel.ITypeDescriptorContext context, System.Globalization.CultureInfo culture, object value, Type destinationType)
            {
                if (value is ");
            this.Write(this.ToStringHelper.ToStringWithCulture(Name));
            this.Write(@" wrappedValue)
                {
                    if (destinationType == WrapperType)
                    {
                        return wrappedValue;
                    }

                    if (destinationType == ValueType)
                    {
                        return wrappedValue.AsPrimitive();
                    }
                }

                return base.ConvertTo(context, culture, value, destinationType);
            }
        }
    }
");
 if (!string.IsNullOrEmpty(Namespace)) { 
            this.Write("}\r\n");
 } 
            return this.GenerationEnvironment.ToString();
        }
    }
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public class CodeTemplateBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
